// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1htENXDZl-LJJTv06iyeS-QqezwfJLHY',
    appId: '1:682578276476:web:4bfdb6e2b8ac279e2499f9',
    messagingSenderId: '682578276476',
    projectId: 'fir-bc735',
    authDomain: 'fir-bc735.firebaseapp.com',
    storageBucket: 'fir-bc735.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwwr7qb8AgdFWjEmPD9HSUdbDz14_JBTg',
    appId: '1:682578276476:android:2984f73291c574fa2499f9',
    messagingSenderId: '682578276476',
    projectId: 'fir-bc735',
    storageBucket: 'fir-bc735.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtTyGU-TZ73dcFmdt66lJOmeo5_jHxll0',
    appId: '1:682578276476:ios:ae0667eec31c2ef32499f9',
    messagingSenderId: '682578276476',
    projectId: 'fir-bc735',
    storageBucket: 'fir-bc735.firebasestorage.app',
    iosBundleId: 'com.example.googles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtTyGU-TZ73dcFmdt66lJOmeo5_jHxll0',
    appId: '1:682578276476:ios:ae0667eec31c2ef32499f9',
    messagingSenderId: '682578276476',
    projectId: 'fir-bc735',
    storageBucket: 'fir-bc735.firebasestorage.app',
    iosBundleId: 'com.example.googles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1htENXDZl-LJJTv06iyeS-QqezwfJLHY',
    appId: '1:682578276476:web:204d30dcd1d4150d2499f9',
    messagingSenderId: '682578276476',
    projectId: 'fir-bc735',
    authDomain: 'fir-bc735.firebaseapp.com',
    storageBucket: 'fir-bc735.firebasestorage.app',
  );
}
